baseurl = "http://elastico.io"
languageCode = "fa-ir"
title = "الستیکو"
copyright = "&copy; کلیه حقوق محفوظ است. بازنشر این مطلب تنها با ذکر آدرس کامل این سایت مجاز است" # Copyright notice. This will be displayed in the footer.
canonifyurls = true
uglyurls = true

[params]
    ga_api_key = "UA-73618104-1" # Google Analytics API key.
    avatar = "../../img/avatar.jpg" # Image should be square, and roughly 150px x 150px
    #bio = "Insert your bio here."
    github = "https://github.com/etcinitd/elastico-io-blog"
    #twitter = "https://twitter.com/username"
    linkedin = "http://www.linkedin.com/groups/7019646"
    #footer_1 = "Some text here."
    #footer_2 = "Some different text here."
    #footer_3 = "Even more different text here."
